package formularios;

import clases.bdConexion;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author laptop-1
 */
public class frmDatosEmpresa extends javax.swing.JInternalFrame {

    bdConexion con;
    
    {
        initComponents();
        comboPais(); //llamada a la funcion comboDepto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        lblModificar = new javax.swing.JLabel();
        lblGuardar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCitas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbPais = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtWhatsaap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFacebook = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtModo = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.control);
        setClosable(true);
        setIconifiable(true);
        setTitle("DATOS CLINCA DENTAL");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXTaskPaneContainer1.setBackground(java.awt.SystemColor.activeCaption);

        jXTaskPane1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Cita.png"))); // NOI18N
        jXTaskPane1.setTitle("OPCIONES");

        lblModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_AddDataBase.png"))); // NOI18N
        lblModificar.setText("Modificar Datos");
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblModificar);

        lblGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_database_save.png"))); // NOI18N
        lblGuardar.setText("Guardar Datos");
        lblGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblGuardar);

        lblEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_database_refresh.png"))); // NOI18N
        lblEliminar.setText("Eliminar Datos");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblEliminar);

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_exit.png"))); // NOI18N
        lblCerrar.setText("Cerrar Ventana");
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblCerrar);

        jXTaskPaneContainer1.add(jXTaskPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 320));

        jTabbedPane1.setBackground(java.awt.SystemColor.activeCaption);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        panelCitas.setBackground(java.awt.SystemColor.activeCaption);

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("RAZON SOCIAL:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 120, 30));

        txtRazonSocial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRazonSocial.setForeground(new java.awt.Color(0, 51, 255));
        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyTyped(evt);
            }
        });
        jPanel3.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 10, 413, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("DIRECCION:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 120, 30));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 51, 255));
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 41, 413, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PAÍS:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 120, 30));

        cmbPais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPais.setForeground(new java.awt.Color(0, 0, 255));
        cmbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaisActionPerformed(evt);
            }
        });
        jPanel3.add(cmbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 72, 165, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CIUDAD:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 72, 70, 30));

        cmbCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCiudad.setForeground(new java.awt.Color(0, 0, 255));
        jPanel3.add(cmbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 72, 165, 30));

        jLabel5.setText("N° IDENT. TRIBUTARIO:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 130, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("N° REGISTRO:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 103, 80, 30));

        txtRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRegistro.setForeground(new java.awt.Color(0, 51, 255));
        txtRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegistroKeyTyped(evt);
            }
        });
        jPanel3.add(txtRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 103, 165, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("TELEFONO:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 120, 30));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 255));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 134, 165, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("WHATSAAP:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 134, 80, 30));

        txtWhatsaap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtWhatsaap.setForeground(new java.awt.Color(0, 51, 255));
        txtWhatsaap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWhatsaapKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWhatsaapKeyTyped(evt);
            }
        });
        jPanel3.add(txtWhatsaap, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 134, 165, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("E-MAIL:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, 120, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 51, 255));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 165, 413, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("FACEBOOK:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, 120, 30));

        txtFacebook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFacebook.setForeground(new java.awt.Color(0, 51, 255));
        txtFacebook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFacebookKeyTyped(evt);
            }
        });
        jPanel3.add(txtFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 196, 413, 30));

        txtNit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNit.setForeground(new java.awt.Color(0, 0, 255));
        jPanel3.add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 103, 165, 30));

        javax.swing.GroupLayout panelCitasLayout = new javax.swing.GroupLayout(panelCitas);
        panelCitas.setLayout(panelCitasLayout);
        panelCitasLayout.setHorizontalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCitasLayout.setVerticalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DATOS CLINICA DENTAL", panelCitas);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 320));
        getContentPane().add(txtModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 144, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked
        // TODO add your handling code here:
        txtModo.setText("1");
        activaControles (true,true,true,true,true,true,true,true,true,true);//procedimiento
        activaBotones(true,false,false);
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        // TODO add your handling code here:
         String v= txtModo.getText();
        
        if (v.equals("0"))//significa que es un nuevo registro
        {
            validarCampos();
        }else
        {
            modificarDatos();
        }    
    }//GEN-LAST:event_lblGuardarMouseClicked

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        // TODO add your handling code here:
        int c = Integer.parseInt(txtCodigo.getText());
        try
        {
            PreparedStatement pstm=(PreparedStatement)
            //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
            con.getConnection().prepareStatement("DELETE datosempresa.* FROM datosempresa WHERE IdEmpresa='"+c+"'");
            pstm.executeUpdate();                
                     
            JOptionPane.showMessageDialog(null,"Registro eliminado exitosamente");
            limpiarControles();
            cargarDatos();
            
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e.getMessage());            
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        cargarDatos();
        txtModo.setVisible(false);
        txtCodigo.setVisible(false);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtRazonSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyReleased
        // convierte a mayusculas
        String rs = txtRazonSocial.getText().toUpperCase();
        txtRazonSocial.setText(rs);
    }//GEN-LAST:event_txtRazonSocialKeyReleased

    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped
        // TODO add your handling code here:

        //limitamos el tamano
        if (txtRazonSocial.getText().length()== 100){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            //Como ves, implementé un beep para que suene si se trata de ingresar mas XD
        }
    }//GEN-LAST:event_txtRazonSocialKeyTyped

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        // convierte a mayusculas
        String d = txtDireccion.getText().toUpperCase();
        txtDireccion.setText(d);
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
        if (txtDireccion.getText().length()== 100){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            //Como ves, implementé un beep para que suene si se trata de ingresar mas XD
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void cmbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisActionPerformed
        // TODO add your handling code here:
        comboCiudad(); //llamda al procedimiento comboMunicipio
    }//GEN-LAST:event_cmbPaisActionPerformed

    private void txtRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistroKeyTyped
        // TODO add your handling code here:
        if (txtRegistro.getText().length()== 15){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            //Como ves, implementé un beep para que suene si se trata de ingresar mas XD
        }
    }//GEN-LAST:event_txtRegistroKeyTyped

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        // SOLO ACEPTA NUMEROS ENTEROS
        char c;
        //capturar el caracter digitado
        c=evt.getKeyChar();
        if(c<'0'|| c>'9')
        {
            evt.consume();//ignora el caracter digitado
        }

        if (txtTelefono.getText().length()== 25){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            //Como ves, implementé un beep para que suene si se trata de ingresar mas XD
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtWhatsaapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhatsaapKeyReleased

    }//GEN-LAST:event_txtWhatsaapKeyReleased

    private void txtWhatsaapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhatsaapKeyTyped
        // TODO add your handling code here:
        // SOLO ACEPTA NUMEROS ENTEROS
        char c;
        //capturar el caracter digitado
        c=evt.getKeyChar();
        if(c<'0'|| c>'9')
        {
            evt.consume();//ignora el caracter digitado
        }

        //limitamos el tamaño
        if (txtWhatsaap.getText().length()== 25){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            //Como ves, implementé un beep para que suene si se trata de ingresar mas XD
        }
    }//GEN-LAST:event_txtWhatsaapKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        if (txtEmail.getText().length()== 50){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            //Como ves, implementé un beep para que suene si se trata de ingresar mas XD
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtFacebookKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacebookKeyTyped
        // TODO add your handling code here:
        if (txtFacebook.getText().length()== 100){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            //Como ves, implementé un beep para que suene si se trata de ingresar mas XD
        }
    }//GEN-LAST:event_txtFacebookKeyTyped

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
         // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    //metodo guardar datos
    private void guardarDatos()
    {
       String rs, dir, pais, ciud, nit, re, tel, wha, em, fb;
       rs=txtRazonSocial.getText();
       dir=txtDireccion.getText();
       nit=txtNit.getText();
       pais=(String) cmbPais.getSelectedItem();
       ciud=(String) cmbCiudad.getSelectedItem();
       re=txtRegistro.getText();
       tel=txtTelefono.getText();
       wha=txtWhatsaap.getText();
       em=txtEmail.getText();
       fb=txtFacebook.getText();
        
        
        try
        {
            PreparedStatement pstm=(PreparedStatement)
            //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
            con.getConnection().prepareStatement("insert into " + " datosempresa(razonSocial, ubicacion, paisEmpresa, ciudadEmpresa, nit, numeroRegistro, telefono, whatsaap, email, facebook)" + "values (?,?,?,?,?,?,?,?,?,?)");
            
            pstm.setString(1, rs);
            pstm.setString(2, dir);
            pstm.setString(3, pais);
            pstm.setString(4, ciud);
            pstm.setString(5, nit);
            pstm.setString(6, re);
            pstm.setString(7, tel);
            pstm.setString(8, wha);
            pstm.setString(9, em);
            pstm.setString(10, fb);
            
            pstm.execute();
            pstm.close();
            
            JOptionPane.showMessageDialog(null,"El registro se guardo correctamente");
        }
        catch(SQLException e)
        {
            System.out.print(e);
        }
    }
    
    //validar los campos antes de guardarlos
     private void validarCampos()
    {
       String rs, dir, nit, ruc, tel, wha;
       rs=txtRazonSocial.getText();
       dir=txtDireccion.getText();
       nit=txtNit.getText();
       ruc=txtRegistro.getText();
       tel=txtTelefono.getText();
       wha=txtWhatsaap.getText();
       
       if (rs.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Escriba el nombre de la Empresa");
           txtRazonSocial.requestFocus();
       }else if(dir.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Especifique la direccion de la Empresa");
           txtDireccion.requestFocus();
       }else if(ruc.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Escriba el numero de Registro de la Empresa");
           txtRegistro.requestFocus();       
       }else if(tel.equals("") && wha.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Escriba al menos un numero de telefono");
           txtTelefono.requestFocus();
       }else
       {
           guardarDatos();
           activaControles(false, false, false, false, false, false, false, false, false, false);
           activaBotones(false, true, true);
       }       
    }
    
     //METODO EXTRAE DATOS DE LA TABLA PAISES Y CONSTRUYE EL COMBOBOX CON LOS PAISES
 public final void comboPais(){
    try
        {
            con = new bdConexion();
            PreparedStatement pstm=(PreparedStatement)
            //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
            con.getConnection().prepareStatement("SELECT * FROM paises");
            ResultSet res=pstm.executeQuery();

           //BUCLE QUE PERMITE LLENAR EL COMBO
            while (res.next())
            {
            cmbPais.addItem (res.getString("Pais"));
            }
            res.close();
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
}//fin combo pais
    
    
    /*METODO EXTRAE DATOS DE LA TABLA ciudades Y CONSTRUYE EL COMBOBOX CON LAS CIUDADES
    TOMANDO COMO BASE EL CODIGO DEL PAIS
  */
 public final void comboCiudad(){

     String pais=(String) cmbPais.getSelectedItem().toString();    
     String codPais = null;
        try
        {
            //con = new bdConexion();
            PreparedStatement pstm=(PreparedStatement)
            //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
            con.getConnection().prepareStatement("SELECT Codigo FROM paises WHERE Pais='"+pais+"'");
            ResultSet res=pstm.executeQuery();	

            //BUCLE QUE PERMITE LLENAR EL COMBO CON LAS CIUDADES PRODUCTO DE LA CONSULTA
            while (res.next())
            {
                codPais = res.getString("Codigo");
            }
            res.close();
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        
        try
        {
            /*CREAMOS LA CONEXION Y REALIZAMOS LA CONSULTA PARA OBTENER LOS DATOS DE LA TABLA ciudades
             SEGUN EL CODIGO DEL PAIS*/
            PreparedStatement pstm=(PreparedStatement)
            //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
            con.getConnection().prepareStatement("SELECT * FROM ciudades WHERE Paises_Codigo='"+codPais+"'ORDER by ciudad ASC");
            ResultSet res1=pstm.executeQuery();

            cmbCiudad.removeAllItems();//REMOVEMOS TODOS LOS ITEMS DEL COMBO

           //BUCLE QUE PERMITE LLENAR EL COMBO CON LAS CIUDADES PRODUCTO DE LA CONSULTA
            while (res1.next())
            {
            cmbCiudad.addItem (res1.getString("Ciudad"));            
            }
            res1.close();
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }    
    }//FIN METODO LLENAR COMBO MUNICIPIO
     
    //activar controles
    public void activaControles(boolean rs, boolean dir, boolean nit, boolean dep, boolean mun, boolean re, boolean tel, boolean wha, boolean em, boolean pw)
    {        
       txtRazonSocial.setEditable(rs);
       txtDireccion.setEditable(dir);
       txtNit.setEditable(nit);
       cmbPais.setEnabled(dep);
       cmbCiudad.setEnabled(mun);
       txtRegistro.setEditable(re);
       txtTelefono.setEditable(tel);
       txtWhatsaap.setEditable(wha);
       txtEmail.setEditable(em);
       txtFacebook.setEditable(pw);
    }
    
    public void activaBotones(boolean g, boolean m, boolean e)
    {
        lblGuardar.setEnabled(g);
        lblEliminar.setEnabled(e);
        lblModificar.setEnabled(m);
    }
 
    
    public void modificarDatos()
    {            
       String c,rs, dir, pa, ciu, nit, re, tel, wha, em, fb;
       c=txtCodigo.getText();
       rs=txtRazonSocial.getText();
       dir=txtDireccion.getText();
       nit=txtNit.getText();
       pa=(String) cmbPais.getSelectedItem();
       ciu=(String) cmbCiudad.getSelectedItem();
       re=txtRegistro.getText();
       tel=txtTelefono.getText();
       wha=txtWhatsaap.getText();
       em=txtEmail.getText();
       fb=txtFacebook.getText();
       
       int cod=Integer.parseInt(c);                      
        try
        {
            //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
            PreparedStatement pstm=(PreparedStatement)
            con.getConnection().prepareStatement("UPDATE datosempresa SET razonSocial='"+rs+"', ubicacion='"+dir+"', paisEmpresa='"+pa+"', ciudadEmpresa='"+ciu+"', nit='"+nit+"', numeroRegistro='"+re+"', telefono='"+tel+"', whatsaap='"+wha+"', email='"+em+"', facebook='"+fb+"' WHERE IdEmpresa='"+cod+"'");
            pstm.executeUpdate();
            pstm.close();
            JOptionPane.showMessageDialog(null, "Los datos se actualizaron correctamente");
            cargarDatos();
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }
    
    //metodo para cargar los datos de la tabla datosempresa
    public void cargarDatos()
    {
        int registros=0;
        //obtener la cantidad de registros que hay en la tabla datosEmpresa
        try
        {
            //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
            PreparedStatement pstm=(PreparedStatement)
            con.getConnection().prepareStatement("SELECT count(1) as total FROM datosempresa");//cuenta el total de registros de la tabla
            ResultSet res=pstm.executeQuery();
            res.next();
            registros = res.getInt("total");
            res.close();
        }
        catch(SQLException e)
        {
         System.out.println(e);   
        }
        
        if (registros<=0)
        {
            //significa que la tabla esta vacia
            txtModo.setText("0");
            
            activaControles(true,true,true,true,true,true,true,true,true,true);
            activaBotones(true, false, false);
            
        }else
        {
            txtModo.setText("1");
            activaControles(false,false,false,false,false,false,false,false,false,false);
            activaBotones(false, true, true);
            
            //realizamos la consulta sql y colocamos los datos en los campos correspondientes
        
            try
            {
                //com.mysql.jdbc.PreparedStatement pstm=(com.mysql.jdbc.PreparedStatement)
                PreparedStatement pstm=(PreparedStatement)
                con.getConnection().prepareStatement("SELECT * FROM datosempresa ORDER BY IdEmpresa");
                ResultSet res=pstm.executeQuery();

                int i=0;

                while (res.next())
                {
                    String estCod = res.getString("IdEmpresa");
                    String estRa = res.getString("razonSocial");
                    String estDir = res.getString("ubicacion");
                    String estPa = res.getString("paisEmpresa");
                    String estCiu = res.getString("ciudadEmpresa");
                    String estNit = res.getString("nit");
                    String estReg = res.getString("numeroRegistro");
                    String estTel = res.getString("telefono");
                    String estWhat = res.getString("whatsaap");
                    String estEm = res.getString("email");
                    String estPW = res.getString("facebook");                

                    txtCodigo.setText(estCod);
                    txtRazonSocial.setText(estRa);
                    txtDireccion.setText(estDir);
                    cmbPais.setSelectedItem(estPa);
                    cmbCiudad.setSelectedItem(estCiu);
                    txtNit.setText(estNit);
                    txtRegistro.setText(estReg);
                    txtTelefono.setText(estTel);
                    txtWhatsaap.setText(estWhat);
                    txtEmail.setText(estEm);
                    txtFacebook.setText(estPW);

                    i++;

                }

                res.close();
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }                                    
        }                
    }
    
    //limpiar los controles al guardar o modificar
    public void limpiarControles()
    {
        txtCodigo.setText("");
        txtRazonSocial.setText("");
        txtDireccion.setText("");
        cmbPais.setSelectedIndex(0);
        cmbCiudad.setSelectedIndex(0);
        txtNit.setText("");
        txtRegistro.setText("");
        txtTelefono.setText("");
        txtWhatsaap.setText("");
        txtEmail.setText("");
        txtFacebook.setText("");
                
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JPanel panelCitas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFacebook;
    private javax.swing.JTextField txtModo;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRegistro;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtWhatsaap;
    // End of variables declaration//GEN-END:variables
}
