package formularios;

import clases.bdConexion;
import clases.medicamentos;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author laptop-1
 */
public class frmMedicamentos extends javax.swing.JInternalFrame {

    bdConexion con;
    medicamentos med = new medicamentos();
    Object[][] dtMedicamentos; //variable de tipo Object que almacena una matriz de datos
    int fila=-1;
    
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        lblNuevo = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblBorrar = new javax.swing.JLabel();
        lblGuardar = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        lblListaMedicamentos = new javax.swing.JLabel();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jcBuscar = new javax.swing.JComboBox();
        txtValorBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        panelPacientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtModo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMedicamentos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MEDICAMENTOS");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jXTaskPaneContainer1.setBackground(java.awt.SystemColor.activeCaption);

        jXTaskPane1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Tratamiento.png"))); // NOI18N
        jXTaskPane1.setTitle("MEDICAMENTOS");

        lblNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNuevo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_AddDataBase.png"))); // NOI18N
        lblNuevo.setText("Nuevo Medicamento");
        lblNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevoMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblNuevo);

        lblModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_database_edit.png"))); // NOI18N
        lblModificar.setText("Modificar Medicamento");
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblModificar);

        lblBorrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBorrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_database_delete.png"))); // NOI18N
        lblBorrar.setText("Borrar Medicamento");
        lblBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBorrarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblBorrar);

        lblGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_database_save.png"))); // NOI18N
        lblGuardar.setText("Guardar Cambios");
        lblGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblGuardar);

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_database_refresh.png"))); // NOI18N
        lblCancelar.setText("Cancelar Cambios");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        jXTaskPane1.getContentPane().add(lblCancelar);

        lblListaMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblListaMedicamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblListaMedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16_ListaPacientes.png"))); // NOI18N
        lblListaMedicamentos.setText("Lista de Medicamentos");
        lblListaMedicamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jXTaskPane1.getContentPane().add(lblListaMedicamentos);

        jXTaskPaneContainer1.add(jXTaskPane1);

        jXTaskPane2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Search.png"))); // NOI18N
        jXTaskPane2.setTitle("Busqueda Por:");
        jXTaskPane2.setPreferredSize(new java.awt.Dimension(176, 150));
        jXTaskPane2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nombreMedicamento" }));
        jXTaskPane2.getContentPane().add(jcBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 30, 165, 30));

        txtValorBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorBuscarKeyTyped(evt);
            }
        });
        jXTaskPane2.getContentPane().add(txtValorBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 85, 165, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Buscar por:");
        jXTaskPane2.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Valor a buscar:");
        jXTaskPane2.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 170, -1));

        jXTaskPaneContainer1.add(jXTaskPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelContenedor.setBackground(java.awt.SystemColor.activeCaption);

        panelPacientes.setBackground(java.awt.SystemColor.activeCaption);
        panelPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Datos Lista de Tratamientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        panelPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Codigo:");
        panelPacientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 25, 98, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Medicamento:");
        panelPacientes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");
        panelPacientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 75, 98, -1));

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 0, 51));
        panelPacientes.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 111, 25));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPacientes.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 330, 25));

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPacientes.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 75, 330, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad en Existencia:");
        panelPacientes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 100, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPacientes.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 91, 25));
        panelPacientes.add(txtModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Precio Unitario:");
        panelPacientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 125, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPacientes.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 125, 91, 25));

        tablaMedicamentos.setBackground(new java.awt.Color(255, 255, 204));
        tablaMedicamentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tablaMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMedicamentos.setRowHeight(25);
        tablaMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedicamentosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMedicamentos);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPacientes.getAccessibleContext().setAccessibleName("Datos Lista de Medicamentos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("SERVICIOS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedicamentosMouseClicked
        // MUESTRA CADA REGISTRO SELECCIONADO EN LOS CAMPOS CORRESPONDIENTES DEL FORMULARIO
        fila= tablaMedicamentos.rowAtPoint(evt.getPoint());//obtiene el indice de la fila seleccionada

        if (fila>-1){

            /*colocamos en los campos del formulario, el valor correspondiente obtenido
             * de la posicion de la fila y de la posicion de la columna. 
            */
            txtCodigo.setText(String.valueOf(tablaMedicamentos.getValueAt(fila, 0)));
            txtNombre.setText(String.valueOf(tablaMedicamentos.getValueAt(fila, 1)));
            txtDescripcion.setText(String.valueOf(tablaMedicamentos.getValueAt(fila, 2)));
            txtCantidad.setText(String.valueOf(tablaMedicamentos.getValueAt(fila, 3)));
            txtPrecio.setText(String.valueOf(tablaMedicamentos.getValueAt(fila, 4)));
                   
        }

        activaOpciones(true,true,true,false,false);//procedimiento
        activaControles (false, false, false, false, false);//procedimiento
    }//GEN-LAST:event_tablaMedicamentosMouseClicked

    private void lblNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoMouseClicked
        // TODO add your handling code here:
        nuevoMedicamento();//procedimiento
    }//GEN-LAST:event_lblNuevoMouseClicked

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked
        // TODO add your handling code here:
        txtModo.setText("1");
       activaOpciones(false,false,false,true,true);//procedimiento
       activaControles(false,true,true,true,true);//procedimiento
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBorrarMouseClicked
        // TODO add your handling code here:
        med.eliminarMedicamento(this.tablaMedicamentos.getValueAt(this.tablaMedicamentos.getSelectedRow(),0).toString());
        updateTabla();//procedimiento
        limpiarObjetos();//procedimiento
    }//GEN-LAST:event_lblBorrarMouseClicked

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        // TODO add your handling code here:
        validarCampos();//procedimiento
    }//GEN-LAST:event_lblGuardarMouseClicked

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        // TODO add your handling code here:
        updateTabla();//procedimiento
        limpiarObjetos();//procedimiento
        activaOpciones (true, false, false, false,false);//procedimiento
        activaControles (false, false, false, false, false);//procedimiento
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        updateTabla();
        limpiarObjetos();
        activaOpciones (true, false, false, false,false);
        activaControles (false, false, false, false, false);
        txtModo.setVisible(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtValorBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorBuscarKeyTyped
        String vBuscar="";
        String vValor="";
        vBuscar = (String) jcBuscar.getSelectedItem();
        vValor = txtValorBuscar.getText();
        try {
            //p.buscarPaciente(vBuscar, vValor);           
            tablaMedicamentos.setModel( med.buscarMedicamento(vBuscar, vValor));
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
            Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtValorBuscarKeyTyped

    //METODO PARA ACTUALIZAR LOS REGISTROS DE LA TABLA
    private void updateTabla(){
       String[] columNames = {"Id_Medicamento", "Nombre", "Descripción", "Cantidad", "Precio Unitario"};
     //usamos la funcion
    dtMedicamentos = med.getDatos();

    // se colocan los datos en la tabla
    DefaultTableModel datos= new DefaultTableModel(dtMedicamentos,columNames);
    tablaMedicamentos.setModel(datos);
    }
    
    //METODO PARA GENERAR NUEVO SERVICIO
    public void nuevoMedicamento()
    {
       txtModo.setText("0");
       
       limpiarObjetos();
       activaOpciones (false, false, false, true,true);
       activaControles (false,true,true, true, true);

       //GENERAR CODIGO DEL SERVICIO AUTOMANTICO
       int registros=0;
       try
        {
            con = new bdConexion();
            PreparedStatement pstm=(PreparedStatement)
            con.getConnection().prepareStatement("SELECT count(1) as total FROM medicamentos");//cuenta el total de registros de la tabla tratamientos
            ResultSet res=pstm.executeQuery();
            res.next();
            registros = res.getInt("total");
            res.close();

            if (registros <=0)//significa que la tabla no tiene ningun registro
            {
                txtCodigo.setText("001");
            }
            else
            {                                  
                con = new bdConexion();
                PreparedStatement pstm1=(PreparedStatement)
                con.getConnection().prepareStatement("SELECT MAX(IdMedicamento) as codigo FROM medicamentos");
                ResultSet res1=pstm1.executeQuery();

                res1.first();
                String v =res1.getString("codigo");

                int cod=(Integer.parseInt(v))+1;

                if ( cod<10)
                {
                    txtCodigo.setText("00000"+cod);
                }
                else if(cod<100)
                {
                    txtCodigo.setText("0000"+cod);
                }
                else if(cod<1000)
                {
                    txtCodigo.setText("000"+cod);
                }
                else if(cod<10000)
                {
                    txtCodigo.setText("00"+cod);
                }
                else if(cod<100000)
                {
                    txtCodigo.setText("0"+cod);
                }
                else
                {
                    txtCodigo.setText(v);
                }

            res1.close();
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }
    
    //METODO GUARDAR TRATAMIENTO
    public void guardarMedicamento()
    {
        String nModo=txtModo.getText();
        int modo=Integer.parseInt(nModo);

        switch (modo)
        {
            case 0:

                    int resp;
                    resp=JOptionPane.showConfirmDialog(null,"¿Desea guardar el registro?","Pregunta",0);

                    if (resp==0)
                    {
                        String cme = txtCodigo.getText();
                        String nme = txtNombre.getText();
                        String desme = txtDescripcion.getText();                        
                        String canme = txtCantidad.getText();                        
                        String preme = txtPrecio.getText();

                        med.nuevoMedicamento(cme, nme, desme, canme, preme);
                        updateTabla();

                        activaOpciones(true,false,false,false,false);
                        activaControles (false, false, false, false, false);
                        limpiarObjetos();

                    }
                    break;
            case 1://SIGNIFICA QUE ES UNA MODIFICACION

                        String cme = txtCodigo.getText();
                        String nme = txtNombre.getText();
                        String desme = txtDescripcion.getText();                        
                        String canme = txtCantidad.getText();                        
                        String preme = txtPrecio.getText();

                        //ENVIAMOS LOS CAMPOS AL CONSTRUCTOR DE LA CLASE TRATAMIENTOS
                        med.modificarMedicamento(cme, nme, desme, canme, preme);
                        
                        //ACTUALIZAMOS LOS CAMPOS DE LA TABLA
                        updateTabla();
                        activaOpciones(true,false,false,false,false);
                        activaControles(false, false, false,false, false);
                        limpiarObjetos();
                        JOptionPane.showMessageDialog(null,"El regisgtro fue actualizado correctamente","Informacion",1);

                        break;
            default: JOptionPane.showMessageDialog(null,"Error al guardar el registro, intente otra vez");
        }
    }
    
        //METODO PARA ACTIVAR O BLOQUEAR LOS CONTROLES USADOS EN EL FORMULARIO
    public void activaControles(boolean cm, boolean nm, boolean dm, boolean cme, boolean pm)
    {
        txtCodigo.setEditable(cm);
        txtNombre.setEditable(nm);
        txtDescripcion.setEditable(dm);
        txtCantidad.setEditable(cme);
        txtPrecio.setEditable(pm);
    }
    
    //METODO PARA ACTIVAR O DESACTIVAR LAS OPCIONES DE CONTROL DEL FORMULARIO
    public void activaOpciones(boolean n, boolean m, boolean e, boolean g, boolean c)
    {
        lblNuevo.setEnabled(n);
        lblModificar.setEnabled(m);
        lblBorrar.setEnabled(e);
        lblGuardar.setEnabled(g);        
        lblCancelar.setEnabled(c);        
    }
    
    //METODO PARA LIMPIAR LOS OBJETOS
    public void limpiarObjetos()
    {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");       
        txtCantidad.setText("");
        txtPrecio.setText("");
    }
    
    //METODO PARA VALIDAR LOS CAMPOS DE TEXTO CUANDO ES UN REGISTRO NUEVO O MODIFICACION
    public void validarCampos()
    {
        
        if (txtNombre.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Escriba el Nombre del medicamento");
            txtNombre.requestFocus();
        }
        else if (txtDescripcion.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Escriba la descripcion del medicamento");
            txtDescripcion.requestFocus();
        }
        else if (txtCantidad.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Escriba la cantidad de existencia del medicamento");
            txtCantidad.requestFocus();
        }else if (txtPrecio.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Escriba el precio del medicamento");
            txtPrecio.requestFocus();
        }
        else
        {
            //SI TODOS LOS CAMPOS ESTAN CORRECTOS, LLAMAMOS AL METODO GUARDAR SERVICIO
            guardarMedicamento();
        } 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private javax.swing.JComboBox jcBuscar;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblListaMedicamentos;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JTable tablaMedicamentos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtModo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtValorBuscar;
    // End of variables declaration//GEN-END:variables
}
